"""initial schema

Revision ID: 4b4622932e10
Revises: 
Create Date: 2026-09-17 10:59:15.890326

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b4622932e10'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---- Enum type definitions (created once, reused by columns) ----
protection_mode_enum = postgresql.ENUM(
    'CONSERVATIVE', 'BALANCED', 'AGGRESSIVE', 'CUSTOM',
    name='protection_mode_enum', create_type=False,
)
user_role_enum = postgresql.ENUM(
    'OWNER', 'ADMIN', 'MEMBER',
    name='user_role_enum', create_type=False,
)
campaign_type_enum = postgresql.ENUM(
    'SEARCH', 'PERFORMANCE_MAX', 'DISPLAY', 'VIDEO', 'SHOPPING',
    name='campaign_type_enum', create_type=False,
)
campaign_status_enum = postgresql.ENUM(
    'ENABLED', 'PAUSED', 'REMOVED',
    name='campaign_status_enum', create_type=False,
)
verdict_enum = postgresql.ENUM(
    'SAFE', 'MONITOR', 'FLAG', 'FRAUD',
    name='verdict_enum', create_type=False,
)
client_verdict_enum = postgresql.ENUM(
    'LEGITIMATE', 'FRAUD',
    name='client_verdict_enum', create_type=False,
)
event_type_enum = postgresql.ENUM(
    'AD_LANDING', 'PAGE_VIEW', 'SCROLL', 'CLICK', 'FORM_START',
    'FORM_SUBMIT', 'PHONE_CLICK', 'OUTBOUND_CLICK',
    'SESSION_START', 'SESSION_END', 'CONVERSION',
    name='event_type_enum', create_type=False,
)
exclusion_status_enum = postgresql.ENUM(
    'PENDING', 'SUBMITTED', 'ACTIVE', 'FAILED', 'REMOVED', 'SKIPPED',
    name='exclusion_status_enum', create_type=False,
)
platform_enum = postgresql.ENUM(
    'GOOGLE', 'META', 'MICROSOFT', 'TIKTOK',
    name='platform_enum', create_type=False,
)
action_type_enum = postgresql.ENUM(
    'ADD_IP_EXCLUSION', 'REMOVE_IP_EXCLUSION', 'ADD_AUDIENCE_EXCLUSION',
    name='action_type_enum', create_type=False,
)
action_status_enum = postgresql.ENUM(
    'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'RETRYING',
    name='action_status_enum', create_type=False,
)
audit_result_enum = postgresql.ENUM(
    'SUCCESS', 'FAILED', 'PENDING',
    name='audit_result_enum', create_type=False,
)

ALL_ENUMS = [
    protection_mode_enum, user_role_enum,
    campaign_type_enum, campaign_status_enum,
    verdict_enum, client_verdict_enum, event_type_enum,
    exclusion_status_enum, platform_enum,
    action_type_enum, action_status_enum, audit_result_enum,
]


def upgrade() -> None:
    bind = op.get_bind()
    for _e in ALL_ENUMS:
        _e.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_reputation',
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('asn', sa.String(length=50), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('is_tor', sa.Boolean(), nullable=False),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('fraud_sessions', sa.Integer(), nullable=False),
    sa.Column('legitimate_sessions', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ip', name=op.f('pk_ip_reputation'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('protection_mode', protection_mode_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('google_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('login_customer_id', sa.String(length=20), nullable=True),
    sa.Column('google_account_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_google_connections_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_connections'))
    )
    op.create_index(op.f('ix_google_connections_organization_id'), 'google_connections', ['organization_id'], unique=False)
    op.create_table('platform_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform', platform_enum, nullable=False),
    sa.Column('action_type', action_type_enum, nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('status', action_status_enum, nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_platform_actions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_actions'))
    )
    op.create_index('ix_platform_actions_org', 'platform_actions', ['organization_id'], unique=False)
    op.create_index('ix_platform_actions_status', 'platform_actions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', user_role_enum, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('require_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_websites_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites'))
    )
    op.create_index(op.f('ix_websites_organization_id'), 'websites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_websites_tracking_token'), 'websites', ['tracking_token'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', audit_result_enum, nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('google_request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('google_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', campaign_type_enum, nullable=False),
    sa.Column('status', campaign_status_enum, nullable=False),
    sa.Column('protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('exclusion_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['google_connections.id'], name=op.f('fk_google_campaigns_connection_id_google_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_campaigns'))
    )
    op.create_index(op.f('ix_google_campaigns_campaign_id'), 'google_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_google_campaigns_connection_id'), 'google_campaigns', ['connection_id'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('visitor_token', sa.String(length=64), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_visitors_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_visitors_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitors'))
    )
    op.create_index(op.f('ix_visitors_organization_id'), 'visitors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visitors_visitor_token'), 'visitors', ['visitor_token'], unique=False)
    op.create_index(op.f('ix_visitors_website_id'), 'visitors', ['website_id'], unique=False)
    op.create_table('exclusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('google_customer_id', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('google_campaign_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', exclusion_status_enum, nullable=False),
    sa.Column('google_resource_name', sa.String(length=255), nullable=True),
    sa.Column('api_request_id', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['google_campaign_id'], ['google_campaigns.id'], name=op.f('fk_exclusions_google_campaign_id_google_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_exclusions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusions')),
    sa.UniqueConstraint('organization_id', 'campaign_id', 'ip_address', name='uq_exclusion_org_campaign_ip')
    )
    op.create_index(op.f('ix_exclusions_campaign_id'), 'exclusions', ['campaign_id'], unique=False)
    op.create_index('ix_exclusions_org_status', 'exclusions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_exclusions_status'), 'exclusions', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('google_campaign_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('asn', sa.String(length=50), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('is_tor', sa.Boolean(), nullable=False),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_duration_seconds', sa.Float(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('scroll_depth', sa.Float(), nullable=False),
    sa.Column('clicks_10_seconds', sa.Integer(), nullable=False),
    sa.Column('clicks_30_seconds', sa.Integer(), nullable=False),
    sa.Column('clicks_60_seconds', sa.Integer(), nullable=False),
    sa.Column('clicks_5_minutes', sa.Integer(), nullable=False),
    sa.Column('clicks_1_hour', sa.Integer(), nullable=False),
    sa.Column('clicks_24_hours', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('verdict', verdict_enum, nullable=False),
    sa.Column('system_verdict', verdict_enum, nullable=False),
    sa.Column('client_verdict', client_verdict_enum, nullable=True),
    sa.Column('final_label', verdict_enum, nullable=True),
    sa.Column('extra_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['google_campaign_id'], ['google_campaigns.id'], name=op.f('fk_sessions_google_campaign_id_google_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], name=op.f('fk_sessions_visitor_id_visitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_sessions_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_gclid'), 'sessions', ['gclid'], unique=False)
    op.create_index(op.f('ix_sessions_google_campaign_id'), 'sessions', ['google_campaign_id'], unique=False)
    op.create_index(op.f('ix_sessions_ip_address'), 'sessions', ['ip_address'], unique=False)
    op.create_index('ix_sessions_org_created', 'sessions', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_sessions_verdict'), 'sessions', ['verdict'], unique=False)
    op.create_index(op.f('ix_sessions_visitor_id'), 'sessions', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_sessions_website_id'), 'sessions', ['website_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', event_type_enum, nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_events_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index('ix_events_session_created', 'events', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('fraud_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('score_contribution', sa.Integer(), nullable=False),
    sa.Column('rule_confidence', sa.Integer(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_fraud_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_fraud_events_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_events'))
    )
    op.create_index('ix_fraud_events_org_created', 'fraud_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_fraud_events_organization_id'), 'fraud_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fraud_events_session_id'), 'fraud_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_events_session_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_organization_id'), table_name='fraud_events')
    op.drop_index('ix_fraud_events_org_created', table_name='fraud_events')
    op.drop_table('fraud_events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index('ix_events_session_created', table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sessions_website_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_visitor_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_verdict'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_index('ix_sessions_org_created', table_name='sessions')
    op.drop_index(op.f('ix_sessions_ip_address'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_google_campaign_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_gclid'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_exclusions_status'), table_name='exclusions')
    op.drop_index('ix_exclusions_org_status', table_name='exclusions')
    op.drop_index(op.f('ix_exclusions_campaign_id'), table_name='exclusions')
    op.drop_table('exclusions')
    op.drop_index(op.f('ix_visitors_website_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_visitor_token'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_organization_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_google_campaigns_connection_id'), table_name='google_campaigns')
    op.drop_index(op.f('ix_google_campaigns_campaign_id'), table_name='google_campaigns')
    op.drop_table('google_campaigns')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_websites_tracking_token'), table_name='websites')
    op.drop_index(op.f('ix_websites_organization_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_platform_actions_status', table_name='platform_actions')
    op.drop_index('ix_platform_actions_org', table_name='platform_actions')
    op.drop_table('platform_actions')
    op.drop_index(op.f('ix_google_connections_organization_id'), table_name='google_connections')
    op.drop_table('google_connections')
    op.drop_table('organizations')
    op.drop_table('ip_reputation')
    # ### end Alembic commands ###

    # Drop enum types last
    for _e in ALL_ENUMS:
        _e.drop(bind, checkfirst=True)
